title: "Nouman Chaudhry"
description: "Data Scientist | AI in Education | Computer Vision | Machine Learning Enthusiast"
theme: jekyll-theme-minimal #jekyll-theme-cayman   # You can change this theme
show_downloads: false

# Social media links (optional)
github_username: noumanschaudhry
linkedin_username: noumanschaudhry
